// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWC04akq2qfZEeernJtAaA-KkS5FS3OD0',
    appId: '1:800143775740:web:ba179f0a23c4f3e48e4479',
    messagingSenderId: '800143775740',
    projectId: 'olien-875f1',
    authDomain: 'olien-875f1.firebaseapp.com',
    storageBucket: 'olien-875f1.firebasestorage.app',
    measurementId: 'G-FQXQKZTZ86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAua-tpEICA6N30toXTTaJUJJzMmIeMqC0',
    appId: '1:800143775740:android:4b724aaa614c1b438e4479',
    messagingSenderId: '800143775740',
    projectId: 'olien-875f1',
    storageBucket: 'olien-875f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJ4iaspO87-al2u25ypmNsOt_BipFIpQ',
    appId: '1:800143775740:ios:c7cc19b70012b2548e4479',
    messagingSenderId: '800143775740',
    projectId: 'olien-875f1',
    storageBucket: 'olien-875f1.firebasestorage.app',
    iosBundleId: 'com.example.fintechui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJ4iaspO87-al2u25ypmNsOt_BipFIpQ',
    appId: '1:800143775740:ios:c7cc19b70012b2548e4479',
    messagingSenderId: '800143775740',
    projectId: 'olien-875f1',
    storageBucket: 'olien-875f1.firebasestorage.app',
    iosBundleId: 'com.example.fintechui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWC04akq2qfZEeernJtAaA-KkS5FS3OD0',
    appId: '1:800143775740:web:24f918ca10b6fe1d8e4479',
    messagingSenderId: '800143775740',
    projectId: 'olien-875f1',
    authDomain: 'olien-875f1.firebaseapp.com',
    storageBucket: 'olien-875f1.firebasestorage.app',
    measurementId: 'G-H5V2MR830M',
  );
}
